await wait(8);
await page.evaluate(() => { const g = window.game; g.cameras.setMode('COCKPIT'); });
await wait(3);
await snap('ck_forward');
await page.evaluate(() => { const g = window.game; g.cameras.lookYawT = 0.0; g.cameras.lookPitchT = -0.55; });
await wait(3);
await snap('ck_down');
await page.evaluate(() => { const g = window.game; g.cameras.lookYawT = 1.1; g.cameras.lookPitchT = -0.75; });
await wait(3);
await snap('ck_left');
await page.evaluate(() => { const g = window.game; g.cameras.lookYawT = -1.1; g.cameras.lookPitchT = -0.75; });
await wait(3);
await snap('ck_right');
await page.evaluate(() => { const g = window.game; g.cameras.setMode('CHASE'); });
await wait(4);
await snap('ext_chase');
