await page.waitForFunction(() => window.game.terrain.pending === 0, null, { timeout: 240000, polling: 500 });
await page.evaluate(() => { const g = window.game; g.time.setHours(15.5);
  const p = g.aircraft.position, q = g.aircraft.quaternion, V = g.camera.position.constructor;
  g.debugCam = { pos: p.clone().add(new V(-5, 3.2, 10).applyQuaternion(q)), target: p.clone().add(new V(0, 1.6, 4.5).applyQuaternion(q)) };
  g.camera.fov = 40; g.camera.updateProjectionMatrix(); });
await wait(3); await snap('st_base');
await page.evaluate(() => { const g = window.game; g.pipeline.params.ao = 0; });
await wait(2); await snap('st_noao');
await page.evaluate(() => { const g = window.game; g.player.model.root.traverse((o) => { if (o.material && o.material.normalScale) o.material.normalScale.set(0, 0); }); });
await wait(2); await snap('st_nonormal');
await page.evaluate(() => { const g = window.game; g.player.model.root.traverse((o) => { o.receiveShadow = false; }); });
await wait(2); await snap('st_noshadow');
