// Generated by scripts/textures.mjs from public/textures/<slug>/<map>.jpg.
// Every entry is CC0 / public domain; provenance in public/textures/CREDITS.md.

export type TexMap = 'albedo' | 'normal' | 'roughness' | 'ao' | 'metalness' | 'height' | 'mask' | 'opacity';

export const TEXTURE_MANIFEST: Record<string, TexMap[]> = {};
