// Regenerates src/assets/textureManifest.ts from public/textures/<slug>/<map>.jpg.
// Usage: node scripts/textures.mjs
import { readdirSync, statSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const MAPS = ['albedo', 'normal', 'roughness', 'ao', 'metalness', 'height', 'mask', 'opacity'];
const root = 'public/textures';
const manifest = {};
let bytes = 0;
if (existsSync(root)) {
  for (const slug of readdirSync(root).sort()) {
    const dir = join(root, slug);
    if (!statSync(dir).isDirectory()) continue;
    const maps = MAPS.filter((m) => existsSync(join(dir, `${m}.jpg`)));
    for (const m of maps) bytes += statSync(join(dir, `${m}.jpg`)).size;
    if (maps.length) manifest[slug] = maps;
  }
}
const body = Object.entries(manifest).map(([s, m]) => `  '${s}': [${m.map((x) => `'${x}'`).join(', ')}],`).join('\n');
writeFileSync(
  'src/assets/textureManifest.ts',
  `// Generated by scripts/textures.mjs from public/textures/<slug>/<map>.jpg.
// Every entry is CC0 / public domain; provenance in public/textures/CREDITS.md.

export type TexMap = 'albedo' | 'normal' | 'roughness' | 'ao' | 'metalness' | 'height' | 'mask' | 'opacity';

export const TEXTURE_MANIFEST: Record<string, TexMap[]> = {${body ? '\n' + body + '\n' : ''}};
`,
);
console.log(`${Object.keys(manifest).length} texture sets, ${(bytes / 1048576).toFixed(2)} MB`);
